source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

use_frameworks!
inhibit_all_warnings!

target ‘MovieDB’ do
pod 'Alamofire'
pod ‘MagicalRecord’
pod 'Kingfisher'
pod 'SVProgressHUD'
pod 'Cosmos', '~> 18.0'

end
