//
//  LocationBlockWorker.swift
//  Qorum
//
//  Created by Stanislav on 31.01.2018.
//  Copyright (c) 2018 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreLocation

class LocationBlockWorker {
    
    func validate(email: String) -> APIResult<Bool> {
        return .value(email.isValidEmail)
    }
    
    func submit(email: String,
                location: CLLocation,
                radius: Double,
                completion: @escaping (LocationBlock.Response)->()) {
        let request = BasicRequest(target: .submitEmail(email: email,
                                                        latitude: location.coordinate.latitude,
                                                        longitude: location.coordinate.longitude,
                                                        radius: radius))
        request.perform { response in
            switch response.result {
            case .value:
                completion(.success)
            case let .error(error):
                completion(.error(error))
            }
        }
    }

}

